#cloud:
#  aws:
#    region:
#      static: sa-east-1
#      auto: false
#    credentials:
#      access-key: fakeAcessKey
#      secret-key: fakeAcessSecret
#    end-point:
#      uri: http://localhost:4566